'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const gate=require('../poc/phase-transition-gate'),registry=require('../poc/task-registry'),{issueDirectorTransitionDecision}=require('../poc/transition-decision-provenance');
process.env.DEEPSEEK_COORDINATOR_SECRET='phase-transition-test-secret';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'phase-gate-')),statePath=path.join(root,'STATE.md'),projectionPath=path.join(root,'strategic-state.json'),architecturePath=path.join(root,'ARCHITECTURE.md'),taskLogPath=path.join(root,'TASK_LOG.md'),researchPath=path.join(root,'research');fs.mkdirSync(researchPath);
const stateText='## Current AI Project State\n\n- **Roadmap / current phase**: phase-2-bounded-coordination / **Phase 2 — Bounded Coordination**, **COMPLETE / INDEPENDENTLY VERIFIED / CONVERGED**.\n- **Unresolved required next work**: phase-3-autonomous-coordination-loop\n\n**Transition evidence**: TASK-PHASE2-VERIFY-001\n';
const state={schema_version:1,roadmap_id:'deepseek-coordinator-evolution-16.6',current_phase:'phase-2-bounded-coordination',phase_status:'CONVERGED',current_strategic_objective:'Phase 2 converged',phase_acceptance_criteria:['phase-2-accepted'],completed_requirements:[{id:'phase-2-bounded-coordination',status:'COMPLETE_INDEPENDENTLY_VERIFIED_CONVERGED'}],unresolved_requirements:[{id:'phase-3-autonomous-coordination-loop',classification:'A',prerequisites:['phase-2-bounded-coordination'],enables:'phase-3-autonomous-coordination-loop',objective_terms:['coordinator'],acceptance_criteria:['phase-3-accepted'],expected_advancement:'Phase 3 activates',convergence_condition:'phase-3-complete'}],required_next_work:['phase-3-autonomous-coordination-loop'],prerequisites:[{id:'phase-2-bounded-coordination',status:'COMPLETE_INDEPENDENTLY_VERIFIED_CONVERGED'}],phase_transition_conditions:['Phase 2 is converged.'],reconciliation_note:'Phase 3 awaits Kyle',authoritative_sources_agree:true};
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(){registry.resetRegistry();state.state_md_sha256=hash(stateText);fs.writeFileSync(statePath,stateText);fs.writeFileSync(projectionPath,JSON.stringify(state,null,2));fs.writeFileSync(architecturePath,'| Stage / Phase | Status | Notes |\n|---|---|---|\n| **Phase 2 — Bounded Coordination** | **COMPLETE** | done |\n| **Phase 3 — Autonomous Coordination Loop** | **FUTURE** | future |\n| **Phase 4 — Future** | **FUTURE** | future |');fs.writeFileSync(taskLogPath,'TASK-PHASE2-VERIFY-001 historical record\n')}
function req(id){return{transition_id:id,current_phase:'phase-2-bounded-coordination',target_phase:'phase-3-autonomous-coordination-loop',requirement_id:'phase-3-autonomous-coordination-loop',acceptance_criteria_id:'phase-2-accepted',convergence_condition:'Phase 2 is converged.',independent_verification_id:'TASK-PHASE2-VERIFY-001',transition_evidence_id:'EVIDENCE-'+id,coordinator_task_id:'TASK-PHASE3-RESEARCH-'+id}}
function record(r,overrides){const provenance=issueDirectorTransitionDecision({decision:'Kyle — Director: OK, move to Phase 3.',currentPhase:r.current_phase,targetPhase:r.target_phase,coordinatorTaskId:r.coordinator_task_id,priorPhaseConvergenceEvidence:'authoritative-state:'+r.current_phase+':CONVERGED',independentVerificationId:r.independent_verification_id,secret:process.env.DEEPSEEK_COORDINATOR_SECRET});if(!provenance.valid)throw new Error(provenance.error);r.transition_id=provenance.record.transition_id;r.transition_evidence_id=provenance.record.transition_evidence_id;const task=registry.createTask({request_id:r.coordinator_task_id,target:'Gemini',task_mode:'RESEARCH_DOCUMENT',workflow_stage:'research',originator:'Kyle',repository:'fluentwithkyle/openclaw-webhook',base_branch:'main',task:'Phase 3 to Phase 4 transition research/reconciliation',constraints:{permitted_paths:['docs/ai/STATE.md','docs/ai/TASK_LOG.md','docs/ai/research/']},authorization:{capabilities:['read_only','modify_files','commit','push']},verification:{required:['independent_verification']},reporting:'json',director_transition_decision_provenance:provenance.record});if(!task.success)throw new Error(task.error);const f={transition_evidence_id:r.transition_evidence_id,transition_id:r.transition_id,current_phase:r.current_phase,target_phase:r.target_phase,prior_phase_convergence_evidence:provenance.record.prior_phase_convergence_evidence,independent_verification_evidence:r.independent_verification_id,director_decision:provenance.record.decision,director_decision_provenance_id:provenance.record.decision_id,director_decision_provenance_signature:provenance.record.signature,coordinator_task_id:r.coordinator_task_id,coordinator_task_origin:'Kyle',...overrides};fs.appendFileSync(taskLogPath,'\n[phase-transition-evidence]\n'+Object.entries(f).map(([k,v])=>k+': '+v).join('\n')+'\n[/phase-transition-evidence]\n')}
const o=()=>({statePath,projectionPath,architecturePath,taskLogPath,researchPath});let n=0;function t(name,fn){try{fn();n++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1}}
fixture();t('valid request structure',()=>assert.equal(gate.requestValid(req('1')).status,'VALID'));
t('valid converged transition succeeds without director_authorization_id',()=>{fixture();const r=req('success');record(r);const x=gate.execute(r,o());assert.equal(x.status,'SUCCESS');assert.equal(x.director_authorization_consumed,undefined);assert.equal(JSON.parse(fs.readFileSync(projectionPath)).state_md_sha256,hash(fs.readFileSync(statePath,'utf8')))});
t('missing durable Director decision evidence is blocked',()=>{fixture();assert.equal(gate.execute(req('missing'),o()).code,'TRANSITION_EVIDENCE_NOT_FOUND')});
t('fabricated and different transition evidence are blocked',()=>{fixture();const r=req('fabricated');record(r,{transition_evidence_id:'OTHER'});assert.equal(gate.execute(r,o()).code,'TRANSITION_EVIDENCE_NOT_FOUND');fixture();record(r,{target_phase:'phase-4-future'});assert.equal(gate.execute(r,o()).code,'TRANSITION_EVIDENCE_MISMATCH')});
t('arbitrary Director text without trusted provenance is blocked',()=>{fixture();const r=req('model');record(r,{director_decision:'Kyle — Director: OK, move to Phase 3.',director_decision_provenance_id:'fabricated',director_decision_provenance_signature:'fabricated'});assert.equal(gate.execute(r,o()).code,'TRANSITION_DECISION_PROVENANCE_MISMATCH')});
t('model-only transition is blocked',()=>{fixture();const r=req('model');record(r,{director_decision:'model authorized: true'});assert.equal(gate.execute(r,o()).code,'TRANSITION_DECISION_PROVENANCE_INVALID')});
t('unregistered coordinator task is blocked',()=>{fixture();const r=req('unregistered');record(r);registry.deleteTask(r.coordinator_task_id);assert.equal(gate.execute(r,o()).code,'TRANSITION_COORDINATOR_TASK_NOT_FOUND')});
t('non-research coordinator task is blocked',()=>{fixture();const r=req('wrong-mode');record(r);const task=registry.getTask(r.coordinator_task_id);task.task_mode='REVIEW';registry.persistCache();assert.equal(gate.execute(r,o()).code,'TRANSITION_COORDINATOR_TASK_INVALID')});
t('invalid signed provenance is blocked',()=>{fixture();const r=req('bad-signature');record(r);const task=registry.getTask(r.coordinator_task_id);task.transition_decision_provenance.signature='bad';registry.persistCache();assert.equal(gate.execute(r,o()).code,'TRANSITION_DECISION_PROVENANCE_INVALID')});
t('evidence from another coordinator decision is blocked',()=>{fixture();const r=req('other-decision');record(r);const other=req('other');record(other);const evidenceFile=fs.readFileSync(taskLogPath,'utf8').replace(r.transition_evidence_id,other.transition_evidence_id).replace(r.transition_id,other.transition_id).replace(r.director_decision_provenance_id||'',other.director_decision_provenance_id||'');fs.writeFileSync(taskLogPath,evidenceFile);assert.equal(gate.execute(r,o()).status,'BLOCKED')});
[['current phase mismatch',r=>r.current_phase='phase-1-observation'],['invalid target',r=>r.target_phase='phase-9'],['skipped target',r=>r.target_phase='phase-4-future'],['missing requirement',r=>r.requirement_id='missing'],['missing acceptance criterion',r=>r.acceptance_criteria_id='missing'],['invalid convergence',r=>r.convergence_condition='fake']].forEach(([name,change])=>t(name,()=>{fixture();const r=req(name);change(r);record(r);assert.equal(gate.execute(r,o()).status,'BLOCKED')}));
t('missing independent verification is blocked',()=>{fixture();const r=req('missing-verification');record(r);fs.writeFileSync(taskLogPath,'unrelated record\n');assert.equal(gate.execute(r,o()).status,'BLOCKED')});
t('unmet prerequisite and stale projection are blocked',()=>{fixture();const p={...state,completed_requirements:[]};p.state_md_sha256=hash(stateText);fs.writeFileSync(projectionPath,JSON.stringify(p));const r=req('pr');record(r);assert.equal(gate.execute(r,o()).status,'BLOCKED');fixture();fs.writeFileSync(projectionPath,JSON.stringify({...state,state_md_sha256:'bad'}));record(r);assert.equal(gate.execute(r,o()).status,'BLOCKED')});
t('failed transition leaves STATE unchanged and projection path rollback is enforced',()=>{fixture();const before=fs.readFileSync(statePath,'utf8'),r=req('atomic');record(r);r.acceptance_criteria_id='bad';assert.equal(gate.execute(r,o()).status,'BLOCKED');assert.equal(fs.readFileSync(statePath,'utf8'),before);fixture();const r2=req('projection');record(r2);assert.equal(gate.execute(r2,{...o(),projectionPath:path.join(root,'missing','projection.json')}).status,'BLOCKED');assert.equal(fs.readFileSync(statePath,'utf8'),before)});
t('roadmap transition does not create or consume Director approval',()=>{fixture();registry.resetRegistry();const approval=registry.createDirectorApproval({request_id:'consequential',target:'Gemini',task_mode:'REVIEW',repository:'fluentwithkyle/openclaw-webhook',base_branch:'main',capabilities:['read_only'],permitted_paths:['poc/']}).approval;const r=req('no-approval');record(r);assert.equal(gate.execute(r,o()).status,'SUCCESS');assert.equal(registry.getDirectorApproval(approval.approval_id).status,'PENDING');registry.resetRegistry()});
t('consequential task authorization remains required',()=>{registry.resetRegistry();const command={request_id:'ordinary',target:'Gemini',task_mode:'BUILDER',repository:'fluentwithkyle/openclaw-webhook',base_branch:'main',authorization:{capabilities:['modify_files']},constraints:{permitted_paths:['poc/']}};assert.equal(registry.consumeDirectorApprovalAndCreateTask(command).success,false);registry.resetRegistry()});
t('gate delegates substantive convergence to strategic-alignment',()=>{fixture();const alignment=require('../poc/strategic-alignment'),original=alignment.evaluateConvergence;alignment.evaluateConvergence=()=>({status:'BLOCKED',code:'TEST_AUTHORITY_OVERRIDE'});const r=req('delegate');record(r);const result=gate.execute(r,o());alignment.evaluateConvergence=original;assert.equal(result.code,'TEST_AUTHORITY_OVERRIDE')});
registry.resetRegistry();fs.rmSync(root,{recursive:true,force:true});console.log(n+' phase-transition-gate tests passed');
