'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
const gate=require('../poc/phase-transition-gate'),registry=require('../poc/task-registry');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'phase-gate-')),statePath=path.join(root,'STATE.md'),projectionPath=path.join(root,'strategic-state.json'),architecturePath=path.join(root,'ARCHITECTURE.md'),taskLogPath=path.join(root,'TASK_LOG.md'),researchPath=path.join(root,'research');fs.mkdirSync(researchPath);
const stateText='## Current AI Project State\n\n- **Roadmap / current phase**: phase-2-bounded-coordination / **Phase 2 — Bounded Coordination**, **COMPLETE / INDEPENDENTLY VERIFIED / CONVERGED**.\n- **Unresolved required next work**: phase-3-autonomous-coordination-loop\n\n**Transition evidence**: TASK-PHASE2-VERIFY-001\n';
const state={schema_version:1,roadmap_id:'deepseek-coordinator-evolution-16.6',current_phase:'phase-2-bounded-coordination',phase_status:'CONVERGED',current_strategic_objective:'Phase 2 converged',phase_acceptance_criteria:['phase-2-accepted'],completed_requirements:[{id:'phase-2-bounded-coordination',status:'COMPLETE_INDEPENDENTLY_VERIFIED_CONVERGED'}],unresolved_requirements:[{id:'phase-3-autonomous-coordination-loop',classification:'A',prerequisites:['phase-2-bounded-coordination'],enables:'phase-3-autonomous-coordination-loop',objective_terms:['coordinator'],acceptance_criteria:['phase-3-accepted'],expected_advancement:'Phase 3 activates',convergence_condition:'phase-3-complete'}],required_next_work:['phase-3-autonomous-coordination-loop'],prerequisites:[{id:'phase-2-bounded-coordination',status:'COMPLETE_INDEPENDENTLY_VERIFIED_CONVERGED'}],phase_transition_conditions:['Phase 2 is converged.'],reconciliation_note:'Phase 3 awaits Kyle',authoritative_sources_agree:true};
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(){state.state_md_sha256=hash(stateText);fs.writeFileSync(statePath,stateText);fs.writeFileSync(projectionPath,JSON.stringify(state,null,2));fs.writeFileSync(architecturePath,'| Stage / Phase | Status | Notes |\n|---|---|---|\n| **Phase 2 — Bounded Coordination** | **COMPLETE** | done |\n| **Phase 3 — Autonomous Coordination Loop** | **FUTURE** | future |\n| **Phase 4 — Future** | **FUTURE** | future |');fs.writeFileSync(taskLogPath,'TASK-PHASE2-VERIFY-001 historical record\n');}
function req(id){return{transition_id:id,current_phase:'phase-2-bounded-coordination',target_phase:'phase-3-autonomous-coordination-loop',requirement_id:'phase-3-autonomous-coordination-loop',acceptance_criteria_id:'phase-2-accepted',convergence_condition:'Phase 2 is converged.',independent_verification_id:'TASK-PHASE2-VERIFY-001',director_authorization_id:''}}
function authReq(id){const r=req(id),binding={transition_id:r.transition_id,current_phase:r.current_phase,target_phase:r.target_phase,requirement_id:r.requirement_id};registry.resetRegistry();r.director_authorization_id=registry.createDirectorApproval({request_id:id,target:'Gemini',task_mode:'REVIEW',repository:'fluentwithkyle/openclaw-webhook',base_branch:'main',capabilities:['read_only'],permitted_paths:['poc/'],transition_binding:binding}).approval.approval_id;return r}
let n=0;function t(name,fn){try{fn();n++;console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1}}
fixture();
t('valid request structure',()=>assert.equal(gate.requestValid(req('1')).status,'VALID'));
const blockedCases=[
['current phase mismatch',r=>r.current_phase='phase-1-observation'],
['invalid target',r=>r.target_phase='phase-9'],
['skipped target',r=>r.target_phase='phase-4-future'],
['missing requirement',r=>r.requirement_id='missing'],
['missing acceptance criterion',r=>r.acceptance_criteria_id='missing'],
['missing independent verification',r=>r.independent_verification_id='missing'],
['invalid convergence',r=>r.convergence_condition='fake'],
['missing authorization',r=>r.director_authorization_id='missing']
];
blockedCases.forEach((item,i)=>t(item[0],()=>{fixture();const r= i===7?req('b'+i):authReq('b'+i);item[1](r);assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED')}));
t('missing prerequisite',()=>{fixture();const p={...state,completed_requirements:[]};p.state_md_sha256=hash(stateText);fs.writeFileSync(projectionPath,JSON.stringify(p,null,2));const r=authReq('pr');assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED')});
t('expired authorization',()=>{fixture();const r=authReq('exp'),a=registry.getDirectorApproval(r.director_authorization_id);a.expiry='2000-01-01T00:00:00.000Z';registry.persistCache();assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED')});
t('reused authorization',()=>{fixture();const r=authReq('reuse');assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'SUCCESS');fixture();assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED')});
t('stale projection',()=>{fixture();const r=authReq('stale');fs.writeFileSync(projectionPath,JSON.stringify({...state,state_md_sha256:'bad'},null,2));assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED')});
t('model-only transition blocked',()=>{fixture();assert.equal(gate.execute(req('model'),{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED')});
t('failed transition leaves STATE unchanged',()=>{fixture();const before=fs.readFileSync(statePath,'utf8'),r=authReq('atomic');r.acceptance_criteria_id='bad';assert.equal(gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath}).status,'BLOCKED');assert.equal(fs.readFileSync(statePath,'utf8'),before)});
t('successful transition matches projection hash',()=>{fixture();const r=authReq('success'),x=gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath});assert.equal(x.status,'SUCCESS');assert.equal(JSON.parse(fs.readFileSync(projectionPath)).state_md_sha256,hash(fs.readFileSync(statePath,'utf8')));assert.equal(registry.getDirectorApproval(r.director_authorization_id).status,'CONSUMED')});
t('historical TASK_LOG remains untouched',()=>{fixture();const before=fs.readFileSync(taskLogPath,'utf8'),r=authReq('history');gate.execute(r,{statePath,projectionPath,architecturePath,taskLogPath,researchPath});assert.equal(fs.readFileSync(taskLogPath,'utf8'),before)});
t('active-phase implementation needs no transition',()=>{fixture();assert.equal(gate.requestValid({current_phase:'phase-2-bounded-coordination'}).status,'BLOCKED')});
t('failed projection path rolls STATE back',()=>{fixture();const before=fs.readFileSync(statePath,'utf8'),r=authReq('projection');assert.equal(gate.execute(r,{statePath,projectionPath:path.join(root,'missing','projection.json'),architecturePath,taskLogPath,researchPath}).status,'BLOCKED');assert.equal(fs.readFileSync(statePath,'utf8'),before)});
registry.resetRegistry();fs.rmSync(root,{recursive:true,force:true});console.log(n+' phase-transition-gate tests passed');
