'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const state = require('../docs/ai/strategic-state.json');
const taskRegistry = require('../poc/task-registry');
const { buildControlPlaneCommand } = require('../services/deepseek-runtime');
const { stateHash, loadAuthoritativeStrategicState, evaluateStrategicAlignment, evaluateCoordinatorIntent, evaluateConvergence } = require('../poc/strategic-alignment');
let passed = 0;
function test(name, fn) { try { fn(); passed++; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}: ${error.message}`); process.exitCode = 1; } }
const requiredObjective = 'Research Phase 4 cross-task lineage navigation';
const required = { roadmap_id: state.roadmap_id, current_phase: state.current_phase, requirement_id: 'phase-4-scaled-conversational-orchestration-cross-task-lineage-navigation', classification: 'A', objective: requiredObjective };
function aligned(proposal = required) { return evaluateStrategicAlignment(state, proposal); }
test('accepts legitimate roadmap-required work pending authorization', () => assert.equal(aligned().status, 'ALIGNED_PENDING_AUTHORIZATION'));
test('accepts legitimate enabling foundation work with authoritative dependency', () => assert.equal(aligned({ ...required, classification: 'A', objective: requiredObjective }).status, 'ALIGNED_PENDING_AUTHORIZATION'));
test('blocks technically valid roadmap-unrelated optimization', () => assert.equal(evaluateCoordinatorIntent('Review caching optimization').status, 'BLOCKED'));
test('blocks technically valid future-phase work without Kyle authorization', () => assert.equal(evaluateCoordinatorIntent('Implement arbitrary unauthorized execution').status, 'BLOCKED'));
test('blocks repeated research recommendation loop', () => assert.equal(evaluateCoordinatorIntent('Research another observation summary').status, 'BLOCKED'));
test('blocks stale roadmap/task description', () => assert.equal(aligned({ ...required, current_phase: 'phase-4' }).status, 'BLOCKED'));
test('blocks conflicting roadmap authority', () => assert.equal(evaluateStrategicAlignment({ ...state, authoritative_sources_agree: false }, required).status, 'BLOCKED'));
test('blocks missing phase completion criteria', () => assert.equal(evaluateStrategicAlignment({ ...state, phase_acceptance_criteria: [] }, required).status, 'BLOCKED'));
test('blocks completed phase with no explicit next requirement', () => assert.equal(evaluateStrategicAlignment({ ...state, required_next_work: [] }, required).status, 'BLOCKED'));
test('blocks false self-attested alignment', () => assert.equal(aligned({ ...required, objective: 'Review unrelated cache' }).status, 'BLOCKED'));
test('blocks alignment pointing to a completed requirement', () => assert.equal(aligned({ ...required, requirement_id: 'phase-3-autonomous-coordination-loop' }).status, 'BLOCKED'));
test('blocks technically passing work without strategic advancement', () => assert.equal(evaluateCoordinatorIntent('Review passing test output').status, 'BLOCKED'));
test('projection/state inconsistency fails closed', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'strategic-')); const statePath = path.join(dir, 'STATE.md'); const projectionPath = path.join(dir, 'state.json'); fs.writeFileSync(statePath, 'canonical'); fs.writeFileSync(projectionPath, JSON.stringify({ ...state, state_md_sha256: 'bad' })); assert.equal(loadAuthoritativeStrategicState({ statePath, projectionPath }).status, 'BLOCKED'); fs.rmSync(dir, { recursive: true }); });
test('projection hash validates canonical state', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'strategic-')); const statePath = path.join(dir, 'STATE.md'); const projectionPath = path.join(dir, 'state.json'); fs.writeFileSync(statePath, 'canonical'); fs.writeFileSync(projectionPath, JSON.stringify({ ...state, state_md_sha256: stateHash('canonical') })); assert.equal(loadAuthoritativeStrategicState({ statePath, projectionPath }).status, 'VALID'); fs.rmSync(dir, { recursive: true }); });
test('fabricated expected advancement cannot align', () => assert.equal(aligned({ ...required, expected_advancement: 'invented' }).expected_advancement, state.unresolved_requirements[0].expected_advancement));
test('fabricated convergence criterion cannot align', () => assert.equal(aligned({ ...required, convergence_criterion: 'invented' }).convergence_condition, state.unresolved_requirements[0].convergence_condition));
test('alignment remains separate from Director authorization and execution', () => { const result = aligned(); assert.equal(result.authorization, 'NOT_GRANTED'); assert.equal(result.execution, 'NOT_STARTED'); });
test('Director-approved consequential work still uses existing TaskRegistry authorization', () => { taskRegistry.resetRegistry(); const command = buildControlPlaneCommand({ operation: 'request_task', objective: requiredObjective }); const approval = taskRegistry.createDirectorApproval({ request_id: command.request_id, repository: command.repository, base_branch: command.base_branch, target: command.target, task_mode: command.task_mode, capabilities: command.authorization.capabilities, permitted_paths: command.constraints.permitted_paths }); command.authorization.approval_id = approval.approval.approval_id; assert.equal(taskRegistry.consumeDirectorApprovalAndCreateTask(command).success, true); taskRegistry.resetRegistry(); });
test('technical completion does not establish convergence', () => assert.equal(evaluateConvergence(state, { requirement_id: required.requirement_id, independent_verification: true }).status, 'BLOCKED'));
test('verified authoritative criteria converge only to Kyle transition escalation', () => assert.equal(evaluateConvergence(state, { mode: 'phase_transition', requirement_id: required.requirement_id, independent_verification: true, acceptance_criteria_id: 'phase-3-autonomous-coordination-implemented', convergence_condition: 'Phase 3 is independently verified and technically converged.' }).status, 'CONVERGED_ESCALATE_TRANSITION'));
console.log(`\n${passed} strategic alignment tests passed`);
